spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentvideo
    username: root
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000 # 1 day
